In [1]:
import pandas as pd
import numpy as np
from helpers import *

from preprocess import *
from implementations import *

In [2]:
data_path = '/Users/don_giraffe/Desktop/ML/project1/dataset_to_release'

In [3]:
x_train, x_test, y_train, train_ids, test_ids = load_csv_data(data_path, sub_sample=True)

In [4]:
# Check the array shape 
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(train_ids.shape)
print(test_ids.shape)

(6563, 321)
(109379, 321)
(6563,)
(6563,)
(109379,)


In [5]:
# see the shape and where na values is 


In [6]:

print(x_train)
print(x_test)
print(y_train)
print(train_ids)
print(test_ids)

[[5.3000000e+01 1.1000000e+01 1.1162015e+07 ...           nan
            nan 2.0000000e+00]
 [4.5000000e+01 7.0000000e+00 7.1620150e+06 ...           nan
            nan 2.0000000e+00]
 [4.0000000e+00 2.0000000e+00 2.2520150e+06 ...           nan
            nan 2.0000000e+00]
 ...
 [2.9000000e+01 6.0000000e+00 6.2620150e+06 ...           nan
            nan           nan]
 [1.9000000e+01 5.0000000e+00 5.1720150e+06 ...           nan
            nan 2.0000000e+00]
 [3.9000000e+01 5.0000000e+00 6.0820150e+06 ...           nan
            nan 2.0000000e+00]]
[[4.4000000e+01 2.0000000e+00 2.0820150e+06 ... 1.0000000e+00
  1.0000000e+00 2.0000000e+00]
 [2.7000000e+01 1.0000000e+00 1.1920150e+06 ...           nan
            nan 2.0000000e+00]
 [3.5000000e+01 5.0000000e+00 5.2620150e+06 ... 1.0000000e+00
  1.0000000e+00 2.0000000e+00]
 ...
 [9.0000000e+00 1.1000000e+01 1.1272015e+07 ... 9.0000000e+00
  9.0000000e+00           nan]
 [1.5000000e+01 1.2000000e+01 1.2122015e+07 ... 1.0000000e+

In [7]:
tX = x_train
y = y_train
ids = train_ids

In [8]:
# For each column
for col in range(tX.shape[1]):
    
    tX_T = np.transpose(tX)

    # Find the positions of missing values in that column
    null = np.isnan(tX_T[col])
    
    # Based on the classification result 'y', find two subsets of missing values
    null_p = np.logical_and(y >= 0, null)  # Subset for positive-classified results
    null_n = np.logical_and(y < 0, null)   # Subset for negative-classified results
    
    # Extract the corresponding subsets
    tX_null = tX[null]         # All rows containing missing values
    tX_null_p = tX[null_p]     # Rows with positive-classified results and missing values
    tX_null_n = tX[null_n]     # Rows with negative-classified results and missing values
    
    # If there are rows containing missing values
    if (tX_null.shape[0] > 0):
        # Print the percentage of missing values in that column
        print('Column', col, 'has {}% missing values'.format(tX_null.shape[0] * 100 / tX.shape[0]))

        # Print the conditional probability P(y = 1|x contains NaN)
        print('P(y = 1|x contains NaN) = {:.3f}%'.format(tX_null_p.shape[0] * 100 / tX_null.shape[0]))
        
        # Print the conditional probability P(y = -1|x contains NaN)
        print('P(y = -1|x contains NaN) = {:.3f}% \n'.format(tX_null_n.shape[0] * 100 / tX_null.shape[0]))

Column 9 has 43.1052872162121% missing values
P(y = 1|x contains NaN) = 6.115%
P(y = -1|x contains NaN) = 93.885% 

Column 10 has 43.1052872162121% missing values
P(y = 1|x contains NaN) = 6.115%
P(y = -1|x contains NaN) = 93.885% 

Column 11 has 99.98476306567119% missing values
P(y = 1|x contains NaN) = 8.549%
P(y = -1|x contains NaN) = 91.451% 

Column 12 has 43.1052872162121% missing values
P(y = 1|x contains NaN) = 6.115%
P(y = -1|x contains NaN) = 93.885% 

Column 13 has 43.1052872162121% missing values
P(y = 1|x contains NaN) = 6.115%
P(y = -1|x contains NaN) = 93.885% 

Column 14 has 99.98476306567119% missing values
P(y = 1|x contains NaN) = 8.549%
P(y = -1|x contains NaN) = 91.451% 

Column 15 has 43.12052415054091% missing values
P(y = 1|x contains NaN) = 6.113%
P(y = -1|x contains NaN) = 93.887% 

Column 16 has 43.18147188785616% missing values
P(y = 1|x contains NaN) = 6.140%
P(y = -1|x contains NaN) = 93.860% 

Column 17 has 43.18147188785616% missing values
P(y = 1|x con

Column 132 has 99.16196861191528% missing values
P(y = 1|x contains NaN) = 8.482%
P(y = -1|x contains NaN) = 91.518% 

Column 133 has 99.16196861191528% missing values
P(y = 1|x contains NaN) = 8.482%
P(y = -1|x contains NaN) = 91.518% 

Column 134 has 99.16196861191528% missing values
P(y = 1|x contains NaN) = 8.482%
P(y = -1|x contains NaN) = 91.518% 

Column 135 has 99.16196861191528% missing values
P(y = 1|x contains NaN) = 8.482%
P(y = -1|x contains NaN) = 91.518% 

Column 136 has 73.68581441413987% missing values
P(y = 1|x contains NaN) = 7.010%
P(y = -1|x contains NaN) = 92.990% 

Column 137 has 97.02879780588145% missing values
P(y = 1|x contains NaN) = 8.103%
P(y = -1|x contains NaN) = 91.897% 

Column 138 has 97.04403474021026% missing values
P(y = 1|x contains NaN) = 8.102%
P(y = -1|x contains NaN) = 91.898% 

Column 139 has 98.90294072832546% missing values
P(y = 1|x contains NaN) = 8.288%
P(y = -1|x contains NaN) = 91.712% 

Column 140 has 97.04403474021026% missing values

Column 295 has 34.14596983087003% missing values
P(y = 1|x contains NaN) = 11.111%
P(y = -1|x contains NaN) = 88.889% 

Column 296 has 34.75544720402255% missing values
P(y = 1|x contains NaN) = 11.048%
P(y = -1|x contains NaN) = 88.952% 

Column 297 has 9.385951546548835% missing values
P(y = 1|x contains NaN) = 6.981%
P(y = -1|x contains NaN) = 93.019% 

Column 299 has 34.86210574432424% missing values
P(y = 1|x contains NaN) = 10.927%
P(y = -1|x contains NaN) = 89.073% 

Column 300 has 35.45634618314795% missing values
P(y = 1|x contains NaN) = 10.872%
P(y = -1|x contains NaN) = 89.128% 

Column 301 has 33.46030778607344% missing values
P(y = 1|x contains NaN) = 11.066%
P(y = -1|x contains NaN) = 88.934% 

Column 302 has 33.81075727563614% missing values
P(y = 1|x contains NaN) = 11.041%
P(y = -1|x contains NaN) = 88.959% 

Column 303 has 34.72497333536492% missing values
P(y = 1|x contains NaN) = 10.970%
P(y = -1|x contains NaN) = 89.030% 

Column 304 has 33.14033216516837% missing

In [9]:
# print(np.isnan(tX[0,319]))
# 找到包含NaN值的列的索引
nan_columns = np.any(np.isnan(tX), axis=0)

# 删除包含NaN值的列
tX_NoNaN = tX[:, ~nan_columns]
tX_NoNaN

array([[5.3000000e+01, 1.1000000e+01, 1.1162015e+07, ..., 1.0000000e+00,
        1.0000000e+00, 1.0000000e+00],
       [4.5000000e+01, 7.0000000e+00, 7.1620150e+06, ..., 2.0000000e+00,
        1.0000000e+00, 1.0000000e+00],
       [4.0000000e+00, 2.0000000e+00, 2.2520150e+06, ..., 2.0000000e+00,
        1.0000000e+00, 1.0000000e+00],
       ...,
       [2.9000000e+01, 6.0000000e+00, 6.2620150e+06, ..., 9.0000000e+00,
        9.0000000e+00, 9.0000000e+00],
       [1.9000000e+01, 5.0000000e+00, 5.1720150e+06, ..., 2.0000000e+00,
        1.0000000e+00, 1.0000000e+00],
       [3.9000000e+01, 5.0000000e+00, 6.0820150e+06, ..., 2.0000000e+00,
        1.0000000e+00, 1.0000000e+00]])

As the dimension of the tX data is high, we first reduce the dimension and then use K-means clustering

In [10]:

def perform_pca(X, n_components=2):
    """
    Perform Principal Component Analysis (PCA) on the input data.

    Args:
    X (numpy.ndarray): The input data matrix where each row represents a sample, and each column represents a feature.
    n_components (int): The number of principal components to retain.

    Returns:
    X_reduced (numpy.ndarray): The reduced-dimensional data.
    """
    # Center the data (subtract the mean)
    mean = np.mean(X, axis=0)
    X_centered = X - mean

    # Calculate the covariance matrix
    cov_matrix = np.cov(X_centered, rowvar=False)

    # Compute eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

    # Select the top n eigenvectors (principal components)
    top_eigenvectors = eigenvectors[:, :n_components]

    # Project the data into the new feature space
    X_reduced = np.dot(X_centered, top_eigenvectors)

    return X_reduced


In [11]:

n_components = 2  # Number of principal components to retain
X_reduced = perform_pca(tX_NoNaN, n_components)
X_reduced.shape

(6563, 2)

In [12]:

def k_means_clustering(X_reduced, n_clusters, max_iterations=100):
    """
    Perform K-Means clustering on reduced-dimensional data.
    
    Args:
    X_reduced (numpy.ndarray): The reduced-dimensional data, where each row represents a sample, and each column represents a reduced feature.
    n_clusters (int): The number of clusters.
    max_iterations (int): Maximum number of iterations.

    Returns:
    cluster_assignment (numpy.ndarray): An array containing cluster labels for each sample.
    """
    np.random.seed(0)
    initial_centers = X_reduced[np.random.choice(X_reduced.shape[0], n_clusters, replace=False)]
                                
    for iteration in range(max_iterations):
        distances = np.linalg.norm(X_reduced[:, np.newaxis] - initial_centers, axis=2)
        cluster_assignment = np.argmin(distances, axis=1)
        
        for cluster in range(n_clusters):
            points_in_cluster = X_reduced[cluster_assignment == cluster]
            if len(points_in_cluster) > 0:
                initial_centers[cluster] = np.mean(points_in_cluster, axis=0)
    
    return cluster_assignment



In [13]:

# Example usage of the function
X_reduced # Example reduced-dimensional data
n_clusters = 3  # Number of clusters
cluster_assignment = k_means_clustering(X_reduced, n_clusters)

In [14]:
cluster_assignment.shape

(6563,)

In [15]:
# Set the missing value threshold
missing_value_threshold = 0.3

# Calculate the number of columns and the count of missing values in each column
column_count = tX.shape[1]
missing_value_count = np.sum(np.isnan(tX), axis=0)

# Calculate the missing value ratio for each column
missing_value_ratio = missing_value_count / tX.shape[0]

# Find the column indices that exceed the threshold
columns_to_remove = np.where(missing_value_ratio > missing_value_threshold)[0]

# Find the column indices that are not removed
columns_to_keep = np.where(missing_value_ratio <= missing_value_threshold)[0]

# Delete the columns that exceed the threshold
tX_cleaned = np.delete(tX, columns_to_remove, axis=1)

# Create an array to display the results
result_array = np.array([
    list(range(column_count)),  # Column Index
    missing_value_ratio,  # Missing Value Ratio
    [idx in columns_to_remove for idx in range(column_count)]], dtype=np.float64).T

# Print the cleaned dataset and the result summary
print("Cleaned Dataset (tX_cleaned):")
print(tX_cleaned)
print("\nColumns Removed Summary (Column Index, Missing Value Ratio, Removed):")
print(result_array)

Cleaned Dataset (tX_cleaned):
[[5.3000000e+01 1.1000000e+01 1.1162015e+07 ... 1.0000000e+00
  1.0000000e+00 2.0000000e+00]
 [4.5000000e+01 7.0000000e+00 7.1620150e+06 ... 1.0000000e+00
  1.0000000e+00 2.0000000e+00]
 [4.0000000e+00 2.0000000e+00 2.2520150e+06 ... 1.0000000e+00
  1.0000000e+00 2.0000000e+00]
 ...
 [2.9000000e+01 6.0000000e+00 6.2620150e+06 ... 9.0000000e+00
  9.0000000e+00           nan]
 [1.9000000e+01 5.0000000e+00 5.1720150e+06 ... 1.0000000e+00
  1.0000000e+00 2.0000000e+00]
 [3.9000000e+01 5.0000000e+00 6.0820150e+06 ... 1.0000000e+00
  1.0000000e+00 2.0000000e+00]]

Columns Removed Summary (Column Index, Missing Value Ratio, Removed):
[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.00000000e+00 0.00000000e+00 0.00000000e+00]

 [3.20000000e+02 9.14216060e-02 0.00000000e+00]]


In [16]:
print(tX_cleaned.shape)

(6563, 144)


In [17]:
# 创建一个函数，用于填充缺失值
def fill_missing_with_mode(matrix, cluster_assignment):
    
    filled_matrix = matrix.copy()
    unique_clusters = np.unique(cluster_assignment)

    for cluster in unique_clusters:
        cluster_indices = np.where(cluster_assignment == cluster)[0]
        cluster_data = matrix[cluster_indices]

        # 计算median
        median = np.nanmedian(cluster_data, axis=0)

        # 找到缺失值的位置
        missing_rows, missing_cols = np.where(np.isnan(cluster_data))

        # 用median填充缺失值
        for row, col in zip(missing_rows, missing_cols):
            filled_matrix[cluster_indices[row], col] = median[col]

    return filled_matrix

# 使用函数填充缺失值
filled_x_matrix = fill_missing_with_mode(tX_cleaned, cluster_assignment)

In [18]:
filled_x_matrix.shape

(6563, 144)

In [19]:
print(filled_x_matrix.shape)
print(x_test)
print(y_train.shape)
print(train_ids)
print(test_ids.shape)

(6563, 144)
[[4.4000000e+01 2.0000000e+00 2.0820150e+06 ... 1.0000000e+00
  1.0000000e+00 2.0000000e+00]
 [2.7000000e+01 1.0000000e+00 1.1920150e+06 ...           nan
            nan 2.0000000e+00]
 [3.5000000e+01 5.0000000e+00 5.2620150e+06 ... 1.0000000e+00
  1.0000000e+00 2.0000000e+00]
 ...
 [9.0000000e+00 1.1000000e+01 1.1272015e+07 ... 9.0000000e+00
  9.0000000e+00           nan]
 [1.5000000e+01 1.2000000e+01 1.2122015e+07 ... 1.0000000e+00
  1.0000000e+00 2.0000000e+00]
 [4.5000000e+01 1.2000000e+01 1.2282015e+07 ...           nan
            nan 2.0000000e+00]]
(6563,)
[     0     50    100 ... 328000 328050 328100]
(109379,)


In [20]:

# normalized_x = normalize(filled_x_matrix)

In [21]:
# 扩展特征矩阵，添加一个截距项
def expand_features(tx):
    n, d = tx.shape
    tx_expanded = np.c_[np.ones((n, 1)), tx]
    return tx_expanded

# 初始化权重向量
def initialize_w(tx_expanded):
    num_features = tx_expanded.shape[1]
    initial_w = np.zeros(num_features)
    return initial_w

# 使用扩展后的特征矩阵和初始化的权重向量
tx_expanded = expand_features(filled_x_matrix)
initial_w = initialize_w(tx_expanded)

In [22]:
contains_nan = np.isnan(filled_x_matrix).any()
contains_nan = np.isnan(initial_w).any()
contains_nan = np.isnan(y_train).any()


if contains_nan:
    print("矩阵包含NaN值")
else:
    print("矩阵不包含NaN值")

矩阵不包含NaN值


In [23]:
from implementations import *

In [24]:
print(initial_w)
print(tx_expanded)
print(y_train)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[[ 1. 53. 11. ...  1.  1.  2.]
 [ 1. 45.  7. ...  1.  1.  2.]
 [ 1.  4.  2. ...  1.  1.  2.]
 ...
 [ 1. 29.  6. ...  9.  9.  2.]
 [ 1. 19.  5. ...  1.  1.  2.]
 [ 1. 39.  5. ...  1.  1.  2.]]
[-1 -1 -1 ...  1 -1 -1]


In [25]:
y_new = np.where(y_train == -1, 0, y_train)
y_new

array([0, 0, 0, ..., 1, 0, 0])

In [26]:
max_iters = 10
gamma = 0.0005
reg = False  # 设置为 True 来应用正则化
lambda_ = 0.1  # 正则化参数

# 定义 compute_lr_gradient 和 compute_lr_loss 函数，或者从其他地方导入

# 调用 logistic_regression_gd 函数执行逻辑回归
final_w, final_loss = logistic_regression_gd(y_new, tx_expanded, initial_w, max_iters, gamma, reg)

# 打印最终的权重和损失
print("Final Weight (w):", final_w)
print("Final Loss:", final_loss)

[-2.07260399e-04 -6.22539235e-03 -1.30367210e-03 -1.34777593e+03
 -1.31746153e-03 -2.98967698e-03 -4.17635037e-01 -2.31167149e-01
 -4.17630798e+05 -4.17630798e+05 -4.86629590e-04 -1.30363401e-02
 -1.34763447e-02 -2.28515923e-04 -2.93691909e-04 -3.96046016e-04
 -3.36317233e-04 -4.91124486e-04 -2.67865306e-04 -2.98453451e-04
 -3.65191224e-04 -4.11854335e-04 -3.92198690e-04 -4.02712174e-04
 -4.01912235e-04 -4.07207070e-04 -3.65267408e-04 -3.87932348e-04
 -4.13835136e-04 -5.89593174e-04 -3.32165168e-04 -4.68154807e-04
 -1.03268322e-03 -2.82264208e-04 -3.96426939e-04 -7.34801158e-04
 -1.28115191e-02 -3.94141399e-03 -2.48171568e-04 -1.52636485e-01
 -1.53563119e-01 -3.86865763e-04 -4.02788359e-04 -4.12463812e-04
 -4.05835746e-04 -3.95398446e-04 -4.11854335e-04 -4.09416425e-04
 -3.46602164e-04 -6.17895779e-04 -1.10544339e-01 -7.50325309e-02
 -4.29163111e-02 -6.49272436e-02 -5.17643989e-02 -6.14988191e-02
 -4.59579461e-02 -2.62608563e-04 -1.26464841e-01 -2.55180558e-04
 -3.35422063e-04 -4.61069

/Users/don_giraffe/Desktop/ML/project1/implementations.py:69: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-t))


ValueError: math domain error